input_sources:
  camera:
    type: pointcloud
    topic: "/camera/depth/color/points"
    queue_size: 1
    publish_on_update: true
    sensor_processor: 
      ignore_points_above: .inf
      ignore_points_below: -.inf
      cutoff_min_depth: 0.1
      cutoff_max_depth: 1.5
      type: structured_light # https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8768489
      normal_factor_a: 0.001063
      normal_factor_b:  0.003949
      normal_factor_c: 0.0
      normal_factor_d: 0.0008278
      normal_factor_e: 1
      lateral_factor: 0.01576 # approx 1 deg

map_frame_id: "world"
robot_base_frame_id: "camera_link"
robot_pose_with_covariance_topic: "/vins_estimator/camera_pose_for_mapping"
robot_pose_cache_size: 200
track_point_frame_id: "camera_link"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0