point_cloud_topic: "/open_quadtree_mapping/pointcloud"
map_frame_id: "body"
robot_base_frame_id: "body"
robot_pose_with_covariance_topic: "/vins_estimator/camera_pose_for_mapping"
robot_pose_cache_size: 200
track_point_frame_id: "body"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
