%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: -0.01
   k2: 0.004
   p1: 5e-5
   p2: -1e-4
projection_parameters:
   fx: 320
   fy: 320
   cx: 320
   cy: 240
