length_in_x: 20
length_in_y: 20
position_x: 0.0
position_y: 0.0
resolution: 0.15
min_variance: 0.000009
max_variance: 0.01
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
enable_visibility_cleanup:                  false
visibility_cleanup_rate:                    1.0